# Project: blog_7myon_com
# Package: 
# Filename: author.py
# Generated: 2020 Oct 11 at 20:54 
# Description of <author>
#
# @author Semyon Mamonov <semyon.mamonov@gmail.com>

from django.views.generic import DetailView
from django.views.generic.base import ContextMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.forms import TextInput

from blog.models import Author

from . import CommonGenericViewsAttributeMixin

from blog.forms.base.author import AuthorModelForm, AuthorFilterForm
from sm_flexdata.views import FilteredListView


class AuthorView(ContextMixin, FilteredListView):

    template_name = 'blog/staff/author/list.html'
    default_filter_form = AuthorFilterForm
    model = Author
    per_page = 20

    def modify_queryset(self, queryset, query_data):
        queryset = queryset.select_related('user')
        return super().modify_queryset(queryset, query_data)

    def setup_autogenerated_filter_form(self, fields):
        super().setup_autogenerated_filter_form(fields)
        email = fields['email']
        email.widget = TextInput(attrs=email.widget.attrs)

    def get_context(self, queryset=None):
        context = super().get_context(queryset)
        context['form'] = context['filter_form']
        return context


class AuthorCommonAttributeMixin(CommonGenericViewsAttributeMixin):
    model = Author
    form_class = AuthorModelForm


class AuthorCreateView(AuthorCommonAttributeMixin, CreateView):
    template_name = 'blog/staff/author/edit.html'


class AuthorDetailView(AuthorCommonAttributeMixin, DetailView):
    template_name = 'blog/staff/author/detail.html'


class AuthorUpdateView(AuthorCommonAttributeMixin, UpdateView):
    template_name = 'blog/staff/author/edit.html'


class AuthorDeleteView(AuthorCommonAttributeMixin, DeleteView):
    template_name = 'blog/staff/author/delete.html'
